# -*- coding: utf-8 -*-
"""Alura Agente ONE AI Tech Builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EHIaCODSTwtxJT_OW6S82PRAaq7eFLj
"""

!pip install google-generativeai PyPDF2 python-dotenv

from google.colab import userdata
GOOGLE_API_KEY = userdata.get('Alura_Agente_2')

from google.colab import files
uploaded = files.upload()

import PyPDF2
import io

def extrair_texto_pdf(nome_arquivo):
    texto = ""
    if isinstance(uploaded[nome_arquivo], bytes):
        arquivo_bytes = io.BytesIO(uploaded[nome_arquivo])
        leitor = PyPDF2.PdfReader(arquivo_bytes)
    else:
        with open(nome_arquivo, 'rb') as arquivo:
            leitor = PyPDF2.PdfReader(arquivo)

    for pagina in leitor.pages:
        texto += pagina.extract_text()
    return texto

# Lista para armazenar o texto de todos os PDFs
textos_dos_pdfs = []
nomes_dos_pdfs = []

for nome_arquivo_uploaded in uploaded.keys():
    try:
        texto_extraido = extrair_texto_pdf(nome_arquivo_uploaded)
        textos_dos_pdfs.append(texto_extraido)
        nomes_dos_pdfs.append(nome_arquivo_uploaded)
        print(f"PDF '{nome_arquivo_uploaded}' carregado! {len(texto_extraido)} caracteres extraídos.")
    except Exception as e:
        print(f"Erro ao processar o arquivo '{nome_arquivo_uploaded}': {e}")

# Concatena todo o texto
todo_o_texto_dos_pdfs = "\n\n".join(textos_dos_pdfs)

import google.generativeai as genai

genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel("models/gemini-flash-latest")

MAX_CONTEXT_LENGTH = 500000

def perguntar_sobre_documento(pergunta):
    prompt = f"""
    Você é um assistente especializado em análise de documentos. Responda a pergunta abaixo
    baseando-se APENAS no conteúdo dos documentos fornecidos.

    DOCUMENTOS:
    {todo_o_texto_dos_pdfs[:MAX_CONTEXT_LENGTH]}

    PERGUNTA: {pergunta}

    INSTRUÇÕES:
    1. Responda de forma clara e direta
    2. Baseie sua resposta APENAS nos documentos fornecidos
    3. Se a resposta não estiver nos documentos, diga "Não encontrei essa informação nos documentos."
    4. Cite trechos dos documentos quando relevante
    """
    resposta = model.generate_content(prompt)
    return resposta.text

pergunta = "No contexto do princípio Dependency Inversion Principle (DIP) , como a Santo Pegasus garante que as classes de serviço dependam de abstrações em vez de implementações concretas?"
resposta = perguntar_sobre_documento(pergunta)
print("📝 Resposta:")
print(resposta)

print("💬 Faça perguntas sobre o PDF (digite 'sair' para encerrar)")
while True:
    pergunta = input("❓ Você: ")
    if pergunta.lower() == 'sair':
        print("👋 Até logo!")
        break
    print("\n🤔 Processando...")
    resposta = perguntar_sobre_documento(pergunta)
    print(f"\n✅ Resposta: {resposta}\n")
    print("-" * 50)