# -*- coding: utf-8 -*-
"""Challenge Alura Agente ONE AI Tech Builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r_aNz2UTLp7lQSAadvYJeKSX8CUmc4CR
"""

!pip install -q -U gradio faiss-cpu sentence-transformers pypdf python-docx google-genai

from google.colab import userdata, drive
from google import genai
import gradio as gr
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from pypdf import PdfReader
from docx import Document
from pathlib import Path
import hashlib
import json
import os
import pickle
import shutil
import threading
import datetime
import time

# ------------------------------------------------------------
# 1. CONFIGURAÇÃO
# ------------------------------------------------------------

drive.mount("/content/drive", force_remount=False)

BASE_DIR = Path("/content/drive/MyDrive/alura_agente_base")
ARQUIVOS_DIR = BASE_DIR / "arquivos"
PASTA_DOCUMENTOS_DRIVE = Path("/content/drive/MyDrive/Agente_Alura_Documentos")
CHUNKS_PATH = BASE_DIR / "chunks.pkl"
METADADOS_PATH = BASE_DIR / "metadados.json"
INDEX_PATH = BASE_DIR / "indice.faiss"
EXPORTS_DIR = BASE_DIR / "exportacoes"

BASE_DIR.mkdir(parents=True, exist_ok=True)
ARQUIVOS_DIR.mkdir(parents=True, exist_ok=True)
PASTA_DOCUMENTOS_DRIVE.mkdir(parents=True, exist_ok=True)
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)

try:
    API_KEY = userdata.get("Alura_Agente_2")
except Exception as exc:
    raise RuntimeError(
        "Crie o Secret Alura_Agente_2 no Google Colab antes de executar."
    ) from exc

if not API_KEY:
    raise RuntimeError("O Secret Alura_Agente_2 está vazio.")

client = genai.Client(api_key=API_KEY)

MODELOS_GEMINI = [
    "gemini-3.6-flash",
    "gemini-3.5-flash",
    "gemini-3.5-flash-lite",
]

embedding_model = SentenceTransformer(
    "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
DIMENSAO = embedding_model.get_sentence_embedding_dimension()

lock = threading.RLock()

todos_chunks = []
metadados_chunks = []
index = faiss.IndexFlatIP(DIMENSAO)


# ------------------------------------------------------------
# 2. EXTRAÇÃO DE TEXTO
# ------------------------------------------------------------

def hash_arquivo(caminho: str) -> str:
    sha = hashlib.sha256()
    with open(caminho, "rb") as arquivo:
        for bloco in iter(lambda: arquivo.read(1024 * 1024), b""):
            sha.update(bloco)
    return sha.hexdigest()


def extrair_texto(caminho: str) -> str:
    caminho_obj = Path(caminho)
    extensao = caminho_obj.suffix.lower()

    if extensao == ".pdf":
        leitor = PdfReader(str(caminho_obj))
        partes = []
        for numero, pagina in enumerate(leitor.pages, start=1):
            texto = pagina.extract_text() or ""
            if texto.strip():
                partes.append(f"[Página {numero}]\n{texto}")
        return "\n\n".join(partes)

    if extensao in {".txt", ".md"}:
        for encoding in ("utf-8", "latin-1"):
            try:
                return caminho_obj.read_text(encoding=encoding)
            except UnicodeDecodeError:
                continue
        raise ValueError(f"Não foi possível identificar a codificação de {caminho_obj.name}.")

    if extensao == ".docx":
        documento = Document(str(caminho_obj))
        return "\n".join(
            paragrafo.text for paragrafo in documento.paragraphs if paragrafo.text.strip()
        )

    raise ValueError(f"Formato não suportado: {extensao}. Use PDF, TXT, MD ou DOCX.")


def criar_chunks(texto: str, tamanho: int = 450, sobreposicao: int = 80):
    palavras = texto.split()
    if not palavras:
        return []
    passo = max(1, tamanho - sobreposicao)
    return [
        " ".join(palavras[inicio:inicio + tamanho])
        for inicio in range(0, len(palavras), passo)
        if palavras[inicio:inicio + tamanho]
    ]


# ------------------------------------------------------------
# 3. PERSISTÊNCIA
# ------------------------------------------------------------

def salvar_base():
    with lock:
        with open(CHUNKS_PATH, "wb") as arquivo:
            pickle.dump(todos_chunks, arquivo)
        METADADOS_PATH.write_text(
            json.dumps(metadados_chunks, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        faiss.write_index(index, str(INDEX_PATH))


def carregar_base():
    global todos_chunks, metadados_chunks, index
    with lock:
        todos_chunks = pickle.load(open(CHUNKS_PATH, "rb")) if CHUNKS_PATH.exists() else []
        metadados_chunks = (
            json.loads(METADADOS_PATH.read_text(encoding="utf-8"))
            if METADADOS_PATH.exists()
            else []
        )

        if len(metadados_chunks) != len(todos_chunks):
            metadados_chunks = [
                {"arquivo": "Documento sem metadados", "hash": "", "chunk": numero}
                for numero in range(len(todos_chunks))
            ]

        if INDEX_PATH.exists():
            index_carregado = faiss.read_index(str(INDEX_PATH))
            if index_carregado.ntotal == len(todos_chunks):
                index = index_carregado
                return

        reconstruir_indice(salvar=False)


def reconstruir_indice(salvar: bool = True):
    global index
    with lock:
        novo_indice = faiss.IndexFlatIP(DIMENSAO)
        if todos_chunks:
            embeddings = embedding_model.encode(
                todos_chunks, normalize_embeddings=True, show_progress_bar=False
            )
            embeddings = np.asarray(embeddings, dtype="float32")
            novo_indice.add(embeddings)
        index = novo_indice
        if salvar:
            salvar_base()


def hashes_existentes():
    return {item.get("hash") for item in metadados_chunks if item.get("hash")}


# ------------------------------------------------------------
# 4. ADIÇÃO E REMOÇÃO DE DOCUMENTOS
# ------------------------------------------------------------

def normalizar_lista_arquivos(arquivos):
    if arquivos is None:
        return []
    if isinstance(arquivos, (str, Path)):
        return [str(arquivos)]
    return [str(item) for item in arquivos]


def adicionar_documentos(arquivos):
    global todos_chunks, metadados_chunks

    caminhos = normalizar_lista_arquivos(arquivos)
    if not caminhos:
        return status_base("Nenhum arquivo selecionado."), listar_documentos()

    adicionados, ignorados, erros = [], [], []
    novos_chunks, novos_metadados = [], []
    hashes = hashes_existentes()

    for caminho in caminhos:
        nome = Path(caminho).name
        try:
            arquivo_hash = hash_arquivo(caminho)
            if arquivo_hash in hashes:
                ignorados.append(f"{nome} (já estava na base)")
                continue

            texto = extrair_texto(caminho)
            if not texto.strip():
                erros.append(f"{nome}: nenhum texto extraível")
                continue

            chunks = criar_chunks(texto)
            if not chunks:
                erros.append(f"{nome}: não gerou trechos")
                continue

            destino = ARQUIVOS_DIR / nome
            if destino.exists():
                destino = ARQUIVOS_DIR / f"{arquivo_hash[:8]}_{nome}"
            shutil.copy2(caminho, destino)

            for numero, chunk in enumerate(chunks, start=1):
                novos_chunks.append(chunk)
                novos_metadados.append(
                    {
                        "arquivo": nome,
                        "caminho_salvo": str(destino),
                        "hash": arquivo_hash,
                        "chunk": numero,
                    }
                )

            hashes.add(arquivo_hash)
            adicionados.append(f"{nome} ({len(chunks)} trechos)")

        except Exception as exc:
            erros.append(f"{nome}: {exc}")

    if novos_chunks:
        with lock:
            todos_chunks.extend(novos_chunks)
            metadados_chunks.extend(novos_metadados)
            embeddings = embedding_model.encode(
                novos_chunks, normalize_embeddings=True, show_progress_bar=False
            )
            embeddings = np.asarray(embeddings, dtype="float32")
            index.add(embeddings)
            salvar_base()

    mensagens = []
    if adicionados:
        mensagens.append("✅ Adicionados: " + "; ".join(adicionados))
    if ignorados:
        mensagens.append("ℹ️ Ignorados: " + "; ".join(ignorados))
    if erros:
        mensagens.append("⚠️ Problemas: " + "; ".join(erros))

    return status_base("\n".join(mensagens)), listar_documentos()


def remover_documento(nome_arquivo):
    """Remove um documento específico (e seus trechos) da base, pelo nome."""
    global todos_chunks, metadados_chunks

    if not nome_arquivo:
        return status_base("Selecione um documento para remover."), listar_documentos()

    with lock:
        indices_manter = [
            i for i, meta in enumerate(metadados_chunks) if meta.get("arquivo") != nome_arquivo
        ]

        if len(indices_manter) == len(metadados_chunks):
            return status_base(f"Documento '{nome_arquivo}' não encontrado."), listar_documentos()

        todos_chunks = [todos_chunks[i] for i in indices_manter]
        metadados_chunks = [metadados_chunks[i] for i in indices_manter]

        caminho_salvo = None
        for meta in metadados_chunks:
            pass  # metadados já filtrados; caminho do arquivo original é buscado abaixo

        # Apaga o arquivo físico salvo em ARQUIVOS_DIR, se existir.
        for arquivo in ARQUIVOS_DIR.glob("*"):
            if arquivo.name == nome_arquivo or arquivo.name.endswith(f"_{nome_arquivo}"):
                arquivo.unlink(missing_ok=True)

        reconstruir_indice(salvar=True)

    return status_base(f"🗑️ Documento removido: {nome_arquivo}"), listar_documentos()


def listar_documentos():
    nomes, vistos = [], set()
    for item in metadados_chunks:
        nome = item.get("arquivo", "Sem nome")
        if nome not in vistos:
            vistos.add(nome)
            nomes.append(nome)
    return gr.update(choices=nomes, value=None)


def status_base(mensagem: str = ""):
    documentos = []
    vistos = set()
    for item in metadados_chunks:
        nome = item.get("arquivo", "Sem nome")
        if nome not in vistos:
            vistos.add(nome)
            documentos.append(nome)

    cabecalho = (
        f"*Base ativa:* {len(documentos)} documento(s), "
        f"{len(todos_chunks)} trecho(s) e {index.ntotal} vetor(es)."
    )
    lista = "\n".join(f"- {nome}" for nome in documentos) or "- Nenhum documento carregado."

    partes = [cabecalho, lista]
    if mensagem:
        partes.insert(0, mensagem)
    return "\n\n".join(partes)


def resolver_pasta_drive(pasta_informada: str = "") -> Path:
    valor = (pasta_informada or "").strip()
    if not valor:
        return PASTA_DOCUMENTOS_DRIVE
    pasta = Path(valor)
    if not pasta.is_absolute():
        pasta = Path("/content/drive/MyDrive") / pasta
    return pasta


def localizar_arquivos_na_pasta(pasta: Path):
    extensoes = {".pdf", ".txt", ".md", ".docx"}
    if not pasta.exists():
        return []
    return sorted(
        str(c) for c in pasta.rglob("*") if c.is_file() and c.suffix.lower() in extensoes
    )


def importar_pasta_drive(pasta_informada: str = ""):
    pasta = resolver_pasta_drive(pasta_informada)
    if not pasta.exists():
        return status_base(f"⚠️ A pasta não foi encontrada: {pasta}"), listar_documentos()

    arquivos = localizar_arquivos_na_pasta(pasta)
    if not arquivos:
        return (
            status_base(f"⚠️ Nenhum PDF, TXT, MD ou DOCX foi encontrado em {pasta}."),
            listar_documentos(),
        )

    resultado, _ = adicionar_documentos(arquivos)
    texto = f"📂 Pasta consultada: {pasta}\n\n🔎 {len(arquivos)} arquivo(s) localizado(s).\n\n{resultado}"
    return texto, listar_documentos()


def importar_pasta_padrao_automaticamente():
    arquivos = localizar_arquivos_na_pasta(PASTA_DOCUMENTOS_DRIVE)
    if arquivos:
        texto, _ = importar_pasta_drive(str(PASTA_DOCUMENTOS_DRIVE))
        return texto
    return status_base(
        f"ℹ️ Pasta padrão pronta: {PASTA_DOCUMENTOS_DRIVE}. "
        "Coloque os documentos nela e clique em *Importar pasta do Drive*."
    )


# ------------------------------------------------------------
# 5. BUSCA SEMÂNTICA E GERAÇÃO (com histórico de conversa)
# ------------------------------------------------------------

def buscar_chunks_relevantes(pergunta: str, k: int = 5):
    with lock:
        if index.ntotal == 0:
            return []
        quantidade = min(k, index.ntotal)
        embedding = embedding_model.encode(
            [pergunta], normalize_embeddings=True, show_progress_bar=False
        )
        embedding = np.asarray(embedding, dtype="float32")
        similaridades, indices = index.search(embedding, quantidade)

        resultados = []
        for posicao, indice_chunk in enumerate(indices[0]):
            if indice_chunk < 0:
                continue
            metadata = metadados_chunks[indice_chunk]
            resultados.append(
                {
                    "texto": todos_chunks[indice_chunk],
                    "arquivo": metadata.get("arquivo", "Documento"),
                    "chunk": metadata.get("chunk", indice_chunk + 1),
                    "similaridade": float(similaridades[0][posicao]),
                }
            )
        return resultados


def gerar_com_fallback(prompt: str) -> str:
    """
    Tenta cada modelo da lista MODELOS_GEMINI em ordem. Em caso de erro 503
    (modelo sobrecarregado — normalmente temporário), faz até 2 novas
    tentativas com espera curta antes de passar para o próximo modelo.
    """
    erros = []
    for modelo in MODELOS_GEMINI:
        tentativas_restantes = 3
        espera = 2

        while tentativas_restantes > 0:
            tentativas_restantes -= 1
            try:
                resposta = client.models.generate_content(model=modelo, contents=prompt)
                texto = getattr(resposta, "text", None)
                if texto:
                    return texto.strip()
                erros.append(f"{modelo}: resposta vazia")
                break
            except Exception as exc:
                sobrecarregado = "503" in str(exc) or "UNAVAILABLE" in str(exc)
                if sobrecarregado and tentativas_restantes > 0:
                    time.sleep(espera)
                    espera *= 2
                    continue
                erros.append(f"{modelo}: {exc}")
                break

    raise RuntimeError(
        "Nenhum modelo Gemini respondeu. Verifique a chave, a cota e os modelos. "
        + " | ".join(erros)
    )


def responder_chat(pergunta, historico):
    """
    Versão com memória: recebe e devolve o histórico do gr.Chatbot no
    formato "messages" (lista de dicionários com 'role' e 'content'),
    e também retorna, em separado, o painel de fontes da última resposta.
    """
    historico = list(historico or [])
    pergunta = (pergunta or "").strip()

    if not pergunta:
        return historico, "", gr.update(value="Sem consulta ainda.")

    if not todos_chunks or index.ntotal == 0:
        aviso = "⚠️ A base está vazia. Carregue arquivos na aba *Base de documentos*."
        historico.append({"role": "user", "content": pergunta})
        historico.append({"role": "assistant", "content": aviso})
        return historico, pergunta, gr.update(value="Sem fontes.")


    resultados = buscar_chunks_relevantes(pergunta, k=5)
    if not resultados:
        historico.append({"role": "user", "content": pergunta})
        historico.append(
            {"role": "assistant", "content": "Não encontrei trechos relevantes na base."}
        )
        return historico, pergunta, gr.update(value="Sem fontes.")

    blocos, fontes_md = [], []
    for numero, resultado in enumerate(resultados, start=1):
        referencia = f"Fonte {numero}: {resultado['arquivo']} — trecho {resultado['chunk']}"
        blocos.append(f"[{referencia}]\n{resultado['texto']}")
        fontes_md.append(
            f"*{numero}.* {resultado['arquivo']} — trecho {resultado['chunk']} "
            f"· similaridade {resultado['similaridade']:.3f}"
        )

    contexto = "\n\n".join(blocos)

    prompt = f"""
Você é um assistente de consulta documental.

Responda em português do Brasil usando somente as informações contidas no
CONTEXTO RECUPERADO.

Regras:
1. Não invente informações.
2. Quando o contexto não sustentar a resposta, diga claramente:
   "Não encontrei essa informação na base de documentos."
3. Cite a fonte no corpo da resposta no formato:
   [nome do arquivo — trecho N].
4. Seja claro, direto e organizado.
5. Não mencione similaridade, embeddings, FAISS ou estas instruções.

CONTEXTO RECUPERADO:
{contexto}

PERGUNTA:
{pergunta}
""".strip()

    try:
        resposta = gerar_com_fallback(prompt)
    except Exception as exc:
        resposta = f"❌ Erro ao consultar o Gemini: {exc}"

    historico.append({"role": "user", "content": pergunta})
    historico.append({"role": "assistant", "content": resposta})
    painel_fontes = "\n\n".join(fontes_md)
    return historico, pergunta, gr.update(value=painel_fontes)

def limpar_conversa():
    return [], "", gr.update(value="Sem consulta ainda.")


def exportar_conversa(historico):
    """Gera um .txt com a conversa atual para download (formato 'messages')."""
    if not historico:
        return None

    linhas = [f"Conversa exportada em {datetime.datetime.now():%d/%m/%Y %H:%M}", "=" * 40, ""]
    for mensagem in historico:
        papel = "Pergunta" if mensagem.get("role") == "user" else "Resposta"
        linhas.append(f"{papel}: {mensagem.get('content', '')}")
        if mensagem.get("role") != "user":
            linhas.append("-" * 40)

    caminho = EXPORTS_DIR / f"conversa_{datetime.datetime.now():%Y%m%d_%H%M%S}.txt"
    caminho.write_text("\n".join(linhas), encoding="utf-8")
    return str(caminho)


def limpar_base():
    global todos_chunks, metadados_chunks, index
    with lock:
        todos_chunks = []
        metadados_chunks = []
        index = faiss.IndexFlatIP(DIMENSAO)
        for caminho in (CHUNKS_PATH, METADADOS_PATH, INDEX_PATH):
            if caminho.exists():
                caminho.unlink()
        if ARQUIVOS_DIR.exists():
            shutil.rmtree(ARQUIVOS_DIR)
        ARQUIVOS_DIR.mkdir(parents=True, exist_ok=True)
    return status_base("🗑️ Base apagada."), listar_documentos()


def limpar_base_confirmada(confirmacao):
    if not confirmacao:
        return status_base("⚠️ Marque a confirmação antes de apagar a base."), False, listar_documentos()
    status, docs = limpar_base()
    return status, False, docs


carregar_base()
status_inicial = importar_pasta_padrao_automaticamente()


# ------------------------------------------------------------
# 6. INTERFACE GRADIO — redesenhada
# ------------------------------------------------------------

css = """
:root {
    --ai-bg-a: #071b1a;
    --ai-bg-b: #0d2b28;
    --ai-teal: #35d6b8;
    --ai-amber: #f2a154;
    --ai-text-soft: #a9d8ce;
    --ai-border: rgba(120, 231, 210, 0.22);
}

.gradio-container {
    background: linear-gradient(160deg, var(--ai-bg-a) 0%, var(--ai-bg-b) 55%, #061615 100%) !important;
    font-family: "Sora", "Inter", sans-serif !important;
}

.header {
    display: flex;
    align-items: center;
    gap: 16px;
    padding: 20px 24px;
    border-bottom: 1px solid var(--ai-border);
    margin-bottom: 16px;
}

.header-logo { width: 58px; height: 58px; flex-shrink: 0; }

.header h1 {
    font-size: 1.85rem;
    margin: 0;
    letter-spacing: 0.03em;
    color: var(--ai-teal) !important;
    text-shadow: 0 0 18px rgba(242, 161, 84, 0.35);
}

.header p { margin: 2px 0 0; color: var(--ai-text-soft) !important; font-size: 0.92rem; }

.gradio-container .panel {
    background: rgba(9, 32, 30, 0.92) !important;
    border: 1px solid var(--ai-border) !important;
    border-radius: 12px !important;
}

/* Trechos de código inline/bloco dentro das respostas do chat (o Gemini
   costuma usar crases para nomes de branch, comandos etc., e o Markdown
   os transforma em <code>/<pre>, que têm fundo e cor próprios). */
.gradio-container code,
.gradio-container pre,
.gradio-container pre code {
    background: rgba(255, 255, 255, 0.10) !important;
    color: #ffe9c7 !important;
    border: 1px solid var(--ai-border) !important;
    border-radius: 4px !important;
    padding: 1px 5px !important;
    font-family: "JetBrains Mono", "Fira Code", monospace !important;
}

.gradio-container pre code {
    display: block !important;
    padding: 10px 12px !important;
}
"""

header_html = """
<div class="header">
    <div class="header-logo">
        <svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Emblema do assistente">
            <defs>
                <linearGradient id="g1" x1="0" y1="0" x2="1" y2="1">
                    <stop offset="0%" stop-color="#35d6b8"/>
                    <stop offset="100%" stop-color="#f2a154"/>
                </linearGradient>
            </defs>
            <g fill="none" stroke="url(#g1)" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="60" cy="60" r="42"/>
                <path d="M60 30v14M60 76v14M30 60h14M76 60h14"/>
                <circle cx="60" cy="60" r="14"/>
            </g>
        </svg>
    </div>
    <div>
        <h1>Alura Agente ONE AI Tech Builder</h1>
        <p>Agente inteligente com base documental persistente e memória de conversa</p>
    </div>
</div>
"""

tema_escuro = gr.themes.Base(
    primary_hue="teal",
    secondary_hue="orange",
    neutral_hue="slate",
).set(
    body_background_fill="#071b1a",
    body_background_fill_dark="#071b1a",
    body_text_color="#eafffb",
    body_text_color_dark="#eafffb",
    body_text_color_subdued="#a9d8ce",
    body_text_color_subdued_dark="#a9d8ce",
    background_fill_primary="#0d2b28",
    background_fill_primary_dark="#0d2b28",
    background_fill_secondary="rgba(255,255,255,0.05)",
    background_fill_secondary_dark="rgba(255,255,255,0.05)",
    border_color_primary="rgba(120,231,210,0.28)",
    border_color_primary_dark="rgba(120,231,210,0.28)",
    block_background_fill="rgba(9,32,30,0.92)",
    block_background_fill_dark="rgba(9,32,30,0.92)",
    block_border_color="rgba(120,231,210,0.22)",
    block_border_color_dark="rgba(120,231,210,0.22)",
    block_label_text_color="#a9d8ce",
    block_label_text_color_dark="#a9d8ce",
    block_title_text_color="#eafffb",
    block_title_text_color_dark="#eafffb",
    input_background_fill="rgba(255,255,255,0.07)",
    input_background_fill_dark="rgba(255,255,255,0.07)",
    input_border_color="rgba(120,231,210,0.28)",
    input_border_color_dark="rgba(120,231,210,0.28)",
    input_placeholder_color="#a9d8ce",
    input_placeholder_color_dark="#a9d8ce",
    button_primary_background_fill="linear-gradient(90deg, #35d6b8, #1fa88f)",
    button_primary_background_fill_dark="linear-gradient(90deg, #35d6b8, #1fa88f)",
    button_primary_text_color="#04211d",
    button_primary_text_color_dark="#04211d",
    button_secondary_background_fill="rgba(53,214,184,0.12)",
    button_secondary_background_fill_dark="rgba(53,214,184,0.12)",
    button_secondary_text_color="#eafffb",
    button_secondary_text_color_dark="#eafffb",
    button_cancel_background_fill="rgba(185,48,64,0.30)",
    button_cancel_background_fill_dark="rgba(185,48,64,0.30)",
    button_cancel_text_color="#fff0f2",
    button_cancel_text_color_dark="#fff0f2",
)

with gr.Blocks(css=css, theme=tema_escuro, title="Alura Agente ONE AI Tech Builder") as demo:
    gr.HTML(header_html)

    with gr.Row():
        with gr.Column(scale=1, min_width=340, elem_classes="panel"):
            gr.Markdown("## 📚 Base de documentos")

            gr.Markdown(
                "### Google Drive\nPasta padrão: Meu Drive/Agente_Alura_Documentos"
            )
            pasta_drive = gr.Textbox(
                label="Pasta do Google Drive",
                value="Agente_Alura_Documentos",
            )
            importar_drive_btn = gr.Button("📂 Importar pasta do Drive", variant="primary")

            gr.Markdown("### Upload manual")
            arquivos_upload = gr.File(
                label="Selecione arquivos para acrescentar",
                file_types=[".pdf", ".txt", ".md", ".docx"],
                file_count="multiple",
                type="filepath",
            )
            adicionar_btn = gr.Button("➕ Adicionar uploads à base", variant="secondary")

            status = gr.Markdown(value=status_inicial)
            atualizar_btn = gr.Button("🔄 Atualizar status")

            gr.Markdown("### Gerenciar documentos")
            documento_selecionado = gr.Dropdown(
                label="Remover um documento específico", choices=[], value=None
            )
            remover_doc_btn = gr.Button("➖ Remover documento selecionado", variant="secondary")

            gr.Markdown("---")
            confirmar_limpeza = gr.Checkbox(label="Confirmo que desejo apagar toda a base")
            apagar_btn = gr.Button("🗑️ Apagar base inteira", variant="stop")

        with gr.Column(scale=2, min_width=520, elem_classes="panel"):
            gr.Markdown("## 💬 Pergunte aos documentos")

            chat = gr.Chatbot(label="Conversa", height=380)

            pergunta = gr.Textbox(
                label="Pergunta",
                placeholder="Ex.: Quais são os principais riscos descritos nos documentos?",
                lines=2,
            )

            with gr.Row():
                enviar_btn = gr.Button("🚀 Enviar pergunta", variant="primary", scale=2)
                limpar_conversa_btn = gr.Button("🧹 Limpar conversa", variant="secondary", scale=1)
                exportar_btn = gr.Button("💾 Exportar conversa", variant="secondary", scale=1)

            arquivo_exportado = gr.File(label="Download da conversa", visible=True)

            gr.Markdown("### 🔎 Fontes da última resposta")
            fontes_painel = gr.Markdown(value="Sem consulta ainda.")

            gr.Examples(
                examples=[
                    ["Quais são os principais temas tratados nos documentos?"],
                    ["Faça um resumo dos pontos mais importantes da base."],
                    ["Quais riscos, recomendações ou conclusões aparecem nos arquivos?"],
                ],
                inputs=pergunta,
            )

    importar_drive_btn.click(
        fn=importar_pasta_drive, inputs=pasta_drive, outputs=[status, documento_selecionado]
    )

    adicionar_btn.click(
        fn=adicionar_documentos, inputs=arquivos_upload, outputs=[status, documento_selecionado]
    ).then(fn=lambda: None, inputs=None, outputs=arquivos_upload)

    atualizar_btn.click(fn=status_base, inputs=None, outputs=status)

    remover_doc_btn.click(
        fn=remover_documento,
        inputs=documento_selecionado,
        outputs=[status, documento_selecionado],
    )

    enviar_btn.click(
        fn=responder_chat, inputs=[pergunta, chat], outputs=[chat, pergunta, fontes_painel]
    )
    pergunta.submit(
        fn=responder_chat, inputs=[pergunta, chat], outputs=[chat, pergunta, fontes_painel]
    )

    limpar_conversa_btn.click(
        fn=limpar_conversa, inputs=None, outputs=[chat, pergunta, fontes_painel]
    )

    exportar_btn.click(fn=exportar_conversa, inputs=chat, outputs=arquivo_exportado)

    apagar_btn.click(
        fn=limpar_base_confirmada,
        inputs=confirmar_limpeza,
        outputs=[status, confirmar_limpeza, documento_selecionado],
    )

print("🚀 Interface pronta.")
print(f"📂 Pasta padrão do Drive: {PASTA_DOCUMENTOS_DRIVE}")
print(status_base())
demo.queue().launch(share=True, debug=True)